<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "universal_content_lists"
 *
 * Auto generated by Extension Builder 2015-01-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Universal Content Lists',
	'description' => 'Create any kind of Lists from standard tt_content. Lists can look like tt_news Lists on a Page, or show Banners/Teasers selected by flexible rules as global Lists.',
	'category' => 'plugin',
	'author' => 'Wolfgang Becker',
	'author_email' => 'wolfgang.becker@visionate.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);