# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2015
  project: Universal Content Lists
  version: 1.0
  release: 1.0
  latex_documents:
  - - Index
    - universal_content_lists.tex
    - Universal Content Lists
    - Wolfgang Becker
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
